controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_treshold: 0.001
    min_y_velocity_treshold: 0.05
    min_theta_velocity_treshold: 0.001
    failure_tolerance: 0.3
    odom_topic: /odom
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]
    progress_checker_plugins: "progress_checker"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      movement_time_aaowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      robot_radius: 0.1
      resolution: 0.05
      always_send_full_costmap: true
      rolling_window: true
      width: 3
      height: 3

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          data_type: "LaserScan"
          topic: /scan
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          combination_method: 1
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55
        cost_scaling_factor: 3.0


