controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.05
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: /odom
    controller_plugins: ["FollowPath"]
    goal_checker_plugins: ["general_goal_checker"]
    progress_checker_plugins: ["progress_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.26
      max_linear_vel: 0.26
      min_linear_vel: 0.05
      max_angular_vel: 1.0
      min_angular_vel: 0.1
      max_lookahead_distance: 0.6
      min_lookahead_distance: 0.3
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 1.8
      use_velocity_scaled_lookahead_dist: true

    local_costmap:
      local_costmap:
        ros__parameters:
          update_frequency: 5.0
          publish_frequency: 2.0
          global_frame: odom
          robot_base_frame: base_link
          use_sim_time: true
          robot_radius: 0.1
          resolution: 0.05
          always_send_full_costmap: true
          rolling_window: true
          width: 3
          height: 3

          plugins: ["obstacle_layer", "inflation_layer"]

          obstacle_layer:
            plugin: "nav2_costmap_2d::ObstacleLayer"
            enabled: true
            observation_sources: scan
            scan:
              data_type: "LaserScan"
              topic: /scan
              max_obstacle_height: 2.0
              marking: true
              clearing: true
              combination_method: 1
              raytrace_max_range: 3.0
              raytrace_min_range: 0.0
              obstacle_max_range: 2.5
              obstacle_min_range: 0.0

          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            enabled: true
            inflation_radius: 0.55
            cost_scaling_factor: 3.0

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: false
      allow_unknown: true
      tolerance: 0.5

    global_costmap:
      global_costmap:
        ros__parameters:
          update_frequency: 1.0
          publish_frequency: 1.0
          global_frame: map
          robot_base_frame: base_link
          use_sim_time: true
          robot_radius: 0.1
          resolution: 0.05
          always_send_full_costmap: true
          track_unknown_space: true

          plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

          static_layer:
            plugin: "nav2_costmap_2d::StaticLayer"
            map_topic: /map
            enabled: true
            map_subscribe_transient_local: true

          obstacle_layer:
            plugin: "nav2_costmap_2d::ObstacleLayer"
            enabled: true
            observation_sources: scan
            scan:
              data_type: "LaserScan"
              topic: /scan
              marking: true
              clearing: true

          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            cost_scaling_factor: 3.0
            inflation_radius: 0.55

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"

recoveries_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
      spin_angle: 3.14
    backup:
      plugin: "nav2_recoveries/BackUp"
      backup_distance: -0.15
      backup_speed: 0.025
    wait:
      plugin: "nav2_recoveries/Wait"
      wait_duration: 5.0