controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: -0.26
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      min_vel_theta: -1.0
      max_vel_theta: 1.0
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.25
      latch_xy_goal_tolerance: false
      
      path_distance_bias: 32.0
      goal_distance_bias: 20.0
      occdist_scale: 0.02
      forward_point_distance: 0.325
      stop_time_buffer: 0.2
      
    local_costmap:
      local_costmap:
        ros__parameters:
          update_frequency: 5.0
          publish_frequency: 2.0
          width: 3.0
          height: 3.0
          resolution: 0.05
          robot_base_frame: base_link
          use_sim_time: true
          rolling_window: true
          plugins: ["voxel_layer", "inflation_layer"]
          voxel_layer:
            plugin: "nav2_costmap_2d::VoxelLayer"
            enabled: true
            observation_sources: scan
            scan:
              data_type: "LaserScan"
              topic: /scan
              marking: true
              clearing: true
          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            cost_scaling_factor: 3.0
            inflation_radius: 0.55

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: true
    
    global_costmap:
      global_costmap:
        ros__parameters:
          use_sim_time: true
          update_frequency: 1.0
          publish_frequency: 1.0
          width: 10.0
          height: 10.0
          resolution: 0.05
          robot_base_frame: base_link
          plugins: ["static_layer", "inflation_layer"]
          static_layer:
            plugin: "nav2_costmap_2d::StaticLayer"
            map_topic: /map
          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            cost_scaling_factor: 3.0
            inflation_radius: 0.55

    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    bt_loop_duration: 10
    default_nav_to_pose_bt_xml: "navigate_w_replanning_and_recovery.xml"
    plugins: ["navigate_to_pose"]

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
      spin_angle: 3.14
    backup:
      plugin: "nav2_recoveries/BackUp"
      backup_distance: -0.15
      backup_speed: 0.025
    wait:
      plugin: "nav2_recoveries/Wait"
      wait_duration: 5.0