planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: false
      allow_unknown: true
      tolerance: 0.5

    global_costmap:
      global_costmap:
        ros__parameters:
          update_frequency: 1.0
          publish_frequency: 1.0
          global_frame: map
          robot_base_frame: base_link
          use_sim_time: true
          robot_radius: 0.1
          resolution: 0.05
          always_send_full_costmap: true
          track_unknown_space: true

          plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

          static_layer:
            plugin: "nav2_costmap_2d::StaticLayer"
            map_topic: /map
            enabled: true
            map_subscribe_transient_local: true

          obstacle_layer:
            plugin: "nav2_costmap_2d::ObstacleLayer"
            enabled: true
            observation_sources: scan
            scan:
              data_type: "LaserScan"
              topic: /scan
              marking: true
              clearing: true

          inflation_layer:
            plugin: "nav2_costmap_2d::InflationLayer"
            cost_scaling_factor: 3.0
            inflation_radius: 0.55